### ISSUE TITLE
什么时候锤子手机可以能正常收到push啊

### ISSUE THREAD

**Issue by shuohao** [MiPushFramework/MiPushFramework#143]
![screenshot_2018-06-19-17-53-13-832](https://user-images.githubusercontent.com/4637107/41590519-c0ae6124-73e9-11e8-9a06-005364b86498.png)
小米推送服务记录里有收到，但是通知栏不会弹出

**Comment by TimothyZhang023** [comment]
没有锤子手机无法调试，so
1. 提供异常日志
**2. 请确认系统没有屏蔽对push的推送消息**

**Comment by shuohao** [comment]
[file.log](https://github.com/Trumeet/MiPushFramework/files/2121842/file.log)
2.确定没有屏蔽

**Comment by TimothyZhang023** [comment]
日志没有问题。
没有屏蔽。

有点怀疑是锤子rom禁止发出没有默认activity的应用发出消息？

**Comment by TimothyZhang023** [comment]
try https://github.com/Trumeet/MiPushFramework/releases/tag/0429112-SNAPSHOT

**Comment by shuohao** [comment]
不行 而且这次还报错 
![screenshot_2018-06-24-20-17-05-826_](https://user-images.githubusercontent.com/4637107/41818991-d225d030-77eb-11e8-80ae-f6cd4d278b33.png)

**Comment by shuohao** [comment]
日志
[file.log](https://github.com/Trumeet/MiPushFramework/files/2130756/file.log)

**Comment by TimothyZhang023** [comment]
rom拦截了之间的读取关系。

**Comment by shuohao** [comment]
@TimothyZhang023 能解决吗

**Comment by TimothyZhang023** [comment]
@shuohao 

小米推送服务记录里有收到，但是通知栏不会弹出 .. 这个我这里无法浮现，确认一下PUSH的通知配置可以设置么？

PUSH服务异常问题还在调查

**Comment by shuohao** [comment]
弹这个toast的时候有个短暂的震动 然后到管理器里看有推送记录

**Comment by shuohao** [comment]
ad46c48-SNAPSHOT 这个版本还是报push服务异常那个错
[file.log](https://github.com/Trumeet/MiPushFramework/files/2140147/file.log)

**Comment by TimothyZhang023** [comment]
服务异常是系统优化限制了应用之间调用。建议关闭锤子里面的优化之类的

**Comment by Songkeys** [comment]
关闭了我能发现的所有优化，但还是不能推送，估计锤子的系统限制太深了……
锤子关闭优化楼主可以参考一下这个帖子试试，不知道我还有没有遗漏：<http://bbs.smartisan.com/thread-917114-1-1.html>

**Comment by TimothyZhang023** [comment]
@Songkeys  锤子不能推送的表现是什么，收不到推送，还是状态栏不显示？

**Comment by Songkeys** [comment]
@TimothyZhang023 
话说锤子原生系统是这样的：如果 app 不挂在后台，推送就收不到。但一旦打开一个，比如微博，一些其他 app 的推送也跟着过来了。不知道是不是安卓都是这样？这些 app 是一个推送联盟的？
然后用了小米推送的这个服务之后，也还是一样的状态，推送一样收，不过貌似走的还是原生系统的那一套？也就是说如果 app 不挂后台就收不到。
另外，我才开始用，不知道这个推送的注册机制是怎样的。是打开 app 后才注册该 app 的推送吗？我目前也打开一大片 app 了，但只有网易云音乐和哔哩哔哩注册了，但不确定是否成功……
![](https://ws4.sinaimg.cn/large/006tNc79gy1ftguy1p6hmj30u01o0q92.jpg)
![](https://ws2.sinaimg.cn/large/006tNc79gy1ftguy6nnbej30u01o0myw.jpg)

**Comment by shuohao** [comment]
@TimothyZhang023 表现是记录里有但是状态栏里没有

**Comment by shuohao** [comment]
![screenshot_2018-07-21-12-14-29-001_](https://user-images.githubusercontent.com/4637107/43032008-c42054e8-8cdf-11e8-8742-b9c94b01f395.png)

**Comment by JameyLee** [comment]
为什么我的m1l连软件都打不开，省电优化没开，还一直提示加入白名单，而且其他权限也都打开了，破锤子也是醉了

**Comment by JameyLee** [comment]
![578505948588226520](https://user-images.githubusercontent.com/38649930/44615375-acde0a80-a86b-11e8-933a-092490fa4ff4.png)

**Comment by shiyunjin** [comment]
m1l的省电优化可以通过 X-APM模块在打盹设置中添加电池忽略名单，添加后名单是看不见的但是已经好使了，但是收不到状态栏收不到推送，只能在小米推送服务这个app的列表看到推送日志

**Comment by shiyunjin** [comment]
而且确定已经关闭了所有优化选项并打开了通知权限，不如试试正常一点的通知请求或者在app里加一个推送测试按钮？

**Comment by TimothyZhang023** [comment]
pls try latest release

**Comment by shiyunjin** [comment]
最新版一样不显示通知，管理器能看见通知，也会震动， 说个奇怪的事情 一直 一直 airdroid在电脑上能收到mipush的通知，但是手机就是没有显示

**Comment by shiyunjin** [comment]
刚刚发现高级设置里面的，显示图标默认开启可是桌面并没有，重新关闭开启后出现了push的图标，等会测试下这样有没有通知

**Comment by shiyunjin** [comment]
还是没有通知。

**Comment by TimothyZhang023** [comment]
> 最新版一样不显示通知，管理器能看见通知，也会震动， 说个奇怪的事情 一直 一直 airdroid在电脑上能收到mipush的通知，但是手机就是没有显示

 通知栏有什么过滤屏蔽功能么？

**Comment by shiyunjin** [comment]
没有，通知权限一直是开启的

**Comment by shiyunjin** [comment]
做个通知测试按钮之类的试试？等大部分软件自己出推送太慢了

**Comment by TimothyZhang023** [comment]
> 做个通知测试按钮之类的试试？等大部分软件自己出推送太慢了

这个可以

**Comment by TimothyZhang023** [comment]
放弃了， 锤子要倒闭了 : ( 换rom吧
