### ISSUE TITLE
关于自动解冻应用的建议

### ISSUE THREAD

**Issue by Zxlusersjly** [MiPushFramework/MiPushFramework#207]
### 问题
一些毒瘤应用，相信应该有不少人会将它们冻结起来，需要用时才解冻。但如此一来，点击收到的推送消息将无法正常打开应用。

### 建议
当检测到应用已冻结时，点击收到的该应用的推送消息自动解冻再打开该应用。

另，如果能接入冰箱/小黑屋/Shizuku的SDK就更好了。

**Comment by Trumeet** [comment]
先扔在这儿吧，稍后想想怎么弄.. 重要性一般（
