### ISSUE TITLE
Android p syb系统 刷入机型模拟无法拨打电话

### ISSUE THREAD

**Issue by qq1064990473** [MiPushFramework/MiPushFramework#264]
syb系统刷入riru的模块之后或直接修改build文件后，会出现无法拨打电话，无法获取信号的问题

**Comment by 805447391** [comment]
edxp黑名单中勾选电话服务即可。

**Comment by TimothyZhang023** [comment]
最新版riru解决了么？

**Comment by Student414** [comment]
最新版riru加edxp已经不需要在edxp黑名单中勾选电话服务了，电话、短信功能正常使用。尚不清楚是电话服务更新的原因还是riru更新的原因。

**Comment by TimothyZhang023** [comment]
ok
