### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by RUYTzzZ** [MiPushFramework/MiPushFramework#267]
我的miui10官方  卸载了小米框架然后装了这个  工作良好但呼吸灯不工作  ，我开了呼吸灯权限（push 的通知qq邮箱分类里面），qq邮箱 应用在后台收到通知会 声音  亮屏  和呼吸灯  不挂后台的情况   push推送的有声音和亮屏，没有呼吸灯。 还有一个问题就是有看记录应用每次启动都会进行注册推送，  也不知道这些是本来如此还是因为不支持miui的缘故

**Comment by TimothyZhang023** [comment]
说了不支持 miui 意思是。不要安装这个。
miui10自带 功能肯定比我们全，为啥不停劝呢。。。。:(
