### ISSUE TITLE
图标问题

### ISSUE THREAD

**Issue by iuyaa** [MiPushFramework/MiPushFramework#271]
请问怎样让状态栏显示应用图标？我的状态栏只显示小米服务框架的图标

**Comment by Trumeet** [comment]
MIUI 吗？如果是，请换 ROM。
不是，请告诉我们你在用什么 ROM。

**Comment by AllenLucas** [comment]
看了下Android M以下就显示的默认图标

**Comment by TimothyZhang023** [comment]
Android M + 还显示应用图标的都是国产垃圾
1. miui 经典菜单栏样式
2. 锤子

说到底这些厂家为了通知栏兼容国产垃圾app，不想让通知icon显示成空白做了一个拙劣的方案，说到底就是一个垃圾兼容另一堆垃圾。建议以后不要买这些品牌手机上 :)
