### ISSUE TITLE
希望增加亮屏功能

### ISSUE THREAD

**Issue by mokapsing** [MiPushFramework/MiPushFramework#272]
如题，希望增加消息推送点亮屏幕功能，可以做单应用/全局开关，用户根据自己需求控制是否亮屏

**Comment by TimothyZhang023** [comment]
消息亮屏 是系统功能。应用不可以决定。

**Comment by yfdyh000** [comment]
应该可以吧，唤醒屏幕。
https://blog.csdn.net/xinpengfei521/article/details/73065769/
https://blog.csdn.net/qq_34161388/article/details/75054140
