### ISSUE TITLE
黑鲨2 Android 9 安装提示INSTALL_FAILED_VERSION_DOWNGRADE错误

### ISSUE THREAD

**Issue by SevenBear0719** [MiPushFramework/MiPushFramework#274]
**Describe the bug/**
A clear and concise description of what the bug is.（解释一下出了什么问题）

**To Reproduce**
Steps to reproduce the behavior:（如何复现错误，也就是您的操作步骤）
1. 
2. 
3. 

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）

**Screenshots**（截图）

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: [e.g. Lineage OS]
 - Android Version: [e.g. 8.1]
 - Version [e.g. 0.3.4 stable]

**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）

**Comment by Trumeet** [comment]
请不要降级。以前装过如需降级请卸载再装。

**Comment by SevenBear0719** [comment]
没有降级，不知道黑鲨2的ROM是不是内置了同样包名的apk，我下的是pre-relase版本的两个APK，我下一下稳定版的试试。。

**Comment by SevenBear0719** [comment]
![Screenshot_2019-05-23-13-57-36-695_com android se](https://user-images.githubusercontent.com/50724468/58228967-e1cbaf00-7d62-11e9-855c-e5ba6ab816f9.png)

<img width="791" alt="QQ20190523-135652@2x" src="https://user-images.githubusercontent.com/50724468/58228983-f1e38e80-7d62-11e9-9818-a70c3ea005bd.png">

@Trumeet 请看截图 下了稳定版的也安装不了

**Comment by Trumeet** [comment]
> ![Screenshot_2019-05-23-13-57-36-695_com android se](https://user-images.githubusercontent.com/50724468/58228967-e1cbaf00-7d62-11e9-855c-e5ba6ab816f9.png)
> 
> <img alt="QQ20190523-135652@2x" width="791" src="https://user-images.githubusercontent.com/50724468/58228983-f1e38e80-7d62-11e9-9818-a70c3ea005bd.png">
> 
> @Trumeet 请看截图 下了稳定版的也安装不了

去设定里面看看有没有内置（

**Comment by SevenBear0719** [comment]
我 aapt了一下 确实有package:com.xiaomi.xmsf这个包，应该是系统内置的，删除不掉，看来是凉了。

**Comment by SevenBear0719** [comment]
如果有兴趣加下QQ 48952291沟通下哈。

**Comment by mokapsing** [comment]
黑鲨内置了小米框架服务

**Comment by TimothyZhang023** [comment]
黑鲨算小米。散了吧，既然内置了就不要安装啦。当然建议安装一个riru模块把品牌伪装成小米
