### ISSUE TITLE
三星S10+root后安装单模块伪装MIUI QQ登录闪退

### ISSUE THREAD

**Issue by ViolentBanana** [MiPushFramework/MiPushFramework#276]
S10+韩版刷了国行rom
不安装单模块伪装,所有应用均不注册
magisk安装了伪装模块儿以后QQ登录会闪退

**Comment by TimothyZhang023** [comment]
riru模块+QQ在我这里没有闪退。
关闭全局模拟会闪退么？

**Comment by ViolentBanana** [comment]
> riru模块+QQ在我这里没有闪退。
> 关闭全局模拟会闪退么？

对  忘了说了 我用的是太极没开全局

**Comment by mokapsing** [comment]
太极的锅
