### ISSUE TITLE
关于坚果pro2s官方rom的通知图标

### ISSUE THREAD

**Issue by Abettoe** [MiPushFramework/MiPushFramework#277]
每个应用的通知的图标都是push的那个图标

![涂鸦_Screenshot_2019-06-26-11-46-56-731](https://user-images.githubusercontent.com/26241099/60149871-d4de2780-9808-11e9-914a-3a3aaa7cc522.jpg)

日志https://1drv.ms/u/s!Asjee9Lwq63NpX0NbNWD5xrUYX5P

**Comment by TimothyZhang023** [comment]
系统决定了 图标，不符合Android 规范。我们无能为力
