### ISSUE TITLE
无法单应用伪装

### ISSUE THREAD

**Issue by Neowww** [MiPushFramework/MiPushFramework#291]
**Describe the bug/**

1.目前是用的是全应用机型伪装，但是掌上生活应用会导致使用环境异常所以想使用单应用伪装。但是每个应用中的单应用伪装开关无法激活，点开之后没有效果，退出再进来开关是处于关闭状态。
2.使用magisk模块后，manager里不勾选全局伪装，应用还是会识别手机品牌为小米。

**Logs**
[logs-2019-58-24-18-58-9.zip](https://github.com/MiPushFramework/MiPushFramework/files/3646814/logs-2019-58-24-18-58-9.zip)

**ROM and version**
 - Name: [Oxygen OS]
 - Android Version: [9]
 - Version [9.5.11]
pusk和manager均为最新pre版本，magisk模块fakemodule版本v9

**Comment by TimothyZhang023** [comment]
你没有点击 右上角 的 ☑️来保存
