### ISSUE TITLE
正在运行的通知能不能隐藏

### ISSUE THREAD

**Issue by a2212997715** [MiPushFramework/MiPushFramework#295]
**Is your feature request related to a problem? Please describe.**（该功能是否与问题有关？请描述）没有关系
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]（简单描述问题所在）
强迫症看着不舒服
**Describe the solution you'd like**（说一下您想解决什么问题，想要做什么）

**Describe alternatives you've considered**（简要描述您考虑过的替代方案）

**Additional context**
Add any other context or screenshots about the feature request here.（更多需要告诉我们的内容）

**Comment by MartisW** [comment]
通知-Push状态![Screenshot_20191106-125500.jpg](https://i.loli.net/2019/11/06/ZCkRaxH9U5NVAhK.jpg)

**Comment by TimothyZhang023** [comment]
8.0+可以隐藏的
