### ISSUE TITLE
[投票] 你希望管理器和推送组件分开，还是合并？

### ISSUE THREAD

**Issue by Trumeet** [MiPushFramework/MiPushFramework#298]
![介绍和对比](https://user-images.githubusercontent.com/17158086/70681141-36773e80-1c4f-11ea-9980-6d4199640de3.png)

（看不到图？ [点这里看国内能打开的链](https://i.loli.net/2019/12/12/5Y1bIJgEKVjahLQ.png) )

你希望项目继续以两个 APP 方式分开，还是合并为一个 APP？（ `com.xiaomi.xmsf` ）？对比和说明已经在图上了。投票持续一个星期。

请点击下面 Emoji 投票。 请勿多次投票，多投会被作废。

* 😁：改为 All in one（合并）
* ❤️：继续分开

**Comment by Trumeet** [comment]
投票测试
/poll 1 2

**Comment by TimothyZhang023** [comment]
all in one 主要还是为了解决一加系统对于跨应用的限制

**Comment by imzf** [comment]
大一统加油

**Comment by Trumeet** [comment]
> 大一统加油

我永远喜欢分离版！

**Comment by MoonBegonia** [comment]
**天下大势，分久必合**

**Comment by mariohide** [comment]
能用就行，吃瓜

**Comment by zhoushangren** [comment]
有一种爱叫放手

**Comment by yfdyh000** [comment]
“我全都要”（想peach~）。

当前是分开，怀疑/担心能上架几个市场，用户覆盖和需求度如何。
如果能自动判断外置Push的存在和版本号…
更期待小米弄好“统一推送”并顺利跟进。本项目所用的SDK好像很久没更新了。

**Comment by TimothyZhang023** [comment]
10的问题修复了，，合并暂时搁浅。当然了  All in one 是获胜方  ：（
