### ISSUE TITLE
Android 10不能注册

### ISSUE THREAD

**Issue by nictse2013** [MiPushFramework/MiPushFramework#301]
原生正式版pe a10
Mi机
以前pie下成功使用
Manager push 2个面具文件都装了
进manager 显示未注册
[logs-2019-13-17-21-13-56.zip](https://github.com/MiPushFramework/MiPushFramework/files/3973634/logs-2019-13-17-21-13-56.zip)

**Comment by nictse2013** [comment]
忘了说，manger应该第一次进有个测试推送，然后在下面 记录 标签 里记录
但我这试了几次都没有，记录 也空空如也

家人的n7没有问题

**Comment by TimothyZhang023** [comment]
模块卸载掉 换新版模块

**Comment by TimothyZhang023** [comment]
https://github.com/TimothyZhang023/MiPushFakeForRiru/releases/tag/v12
