### ISSUE TITLE
Android 10 推送有记录但无通知

### ISSUE THREAD

**Issue by AkinoMaple** [MiPushFramework/MiPushFramework#303]
**Describe the bug/**
A clear and concise description of what the bug is.（解释一下出了什么问题）
在高级设置中模拟消息到达却无消息
酷安等多款应用在有推送成功的记录 但是并没有接到通知
**To Reproduce**
Steps to reproduce the behavior:（如何复现错误，也就是您的操作步骤）
1. 酷安中有人回复消息

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）

**Screenshots**（截图）
![Screenshot_20200101-091526_](https://user-images.githubusercontent.com/26006258/71637163-64143e00-2c77-11ea-91e4-9aa4c8f1c5a4.png)

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: Evolution X
 - Android Version: 10.0
 - Version 3.5 20191226-0407

**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）

**Comment by TimothyZhang023** [comment]
“在高级设置中模拟消息到达却无消息”

你看看是不是你关闭了通知权限了。:( 还是不行的话，抓一段adb log吧。就点击高级通知的时候

**Comment by AkinoMaple** [comment]
我换了部手机…可以接到了
