### ISSUE TITLE
无法安装push

### ISSUE THREAD

**Issue by sovzzz** [MiPushFramework/MiPushFramework#306]
黑鲨2pro 安卓9
manager一直显示正在连接。
无法接受到推送。

**Comment by sovzzz** [comment]
然后push我是用安装狮装的，不知道是否安装成功了。准备卸载重装的时候发现push在系统应用里，没法卸载

**Comment by sovzzz** [comment]
我怀疑可能是黑鲨自带push，mipush里的push没有安装成功，或是安装了但没法正常运行。

**Comment by TimothyZhang023** [comment]
MIUI需要卸载系统自带，黑鲨同理
另外不建议小米安装这个模块
