### ISSUE TITLE
Push的Xposed模块在安卓10上不起作用

### ISSUE THREAD

**Issue by KonnoYuuki-SU** [MiPushFramework/MiPushFramework#309]
**Describe the bug/**
A clear and concise description of what the bug is.（解释一下出了什么问题）
Push的Xposed模块在安卓10上不起作用，XP框架是[Edxposed v0.5.6.0_beta(4471)(YAHFA)]
无论是全局伪装小米设备 或者是单个伪装小米设备，操作都不会生效（已给Root权限）

**Expected behavior**
A clear and concise description of what you expected to happen.（您希望发生什么）

**Screenshots**（截图）

**Logs** （日志）
Logs are very important, this can help us solve the problem.
Please upload your log file and paste the address here:（请上传您的日志文件，在这里粘贴地址：）

**ROM and version(manager):** （你的 ROM 和 manager 的版本）
 - Name: [Havoc-OS]
 - Android Version: [10]
 - Version [3.1]

**Additional context**
Add any other context about the problem here.（更多关于问题的内容写在这里）

**Comment by sky96111** [comment]
是，而且伪装状态会自动关闭（其实他在工作。。）没看懂为什么鱼塔关掉了喵喵的pr
