### ISSUE TITLE
建议：加入 F-Droid 仓库

### ISSUE THREAD

**Issue by Iey4iej3** [MiPushFramework/MiPushFramework#353]
很多开源 Android 项目会维护一个 F-Droid 上的编译 bot，建议加入。

**Comment by eebssk1** [comment]
小米的sdk不开源吧。

**Comment by linsui** [comment]
https://github.com/MiPushFramework/MiPushFramework/tree/master/push/libs 这个 jar 应该不是开源的所以无法发布到 F-Droid。
