### ISSUE TITLE
Icebox SDK 不可用

### ISSUE THREAD

**Issue by Zxilly** [MiPushFramework/MiPushFramework#363]
https://dl.bintray.com/rikkaw/Libraries/com/catchingnow/icebox/SDK/1.0.5/SDK-1.0.5.pom 返回 403
![image](https://user-images.githubusercontent.com/31370133/132094504-8d37306f-fb29-44e5-9d34-4b122d98961b.png)

**Comment by yfdyh000** [comment]
用 https://jitpack.io/#heruoxin/IceBox-SDK/55dd857d74
